server {
    listen 80;
    server_name glsvision2047.com www.glsvision2047.com enquiry.glsvision2047.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name glsvision2047.com www.glsvision2047.com;

    ssl_certificate /etc/letsencrypt/live/glsvision2047.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/glsvision2047.com/privkey.pem;

    root /var/www/html;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    location /exhibition {
        alias /var/www/html/exhibition;
        index index.html;
        try_files $uri $uri/ /exhibition/index.html;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    }

    location ~ /\.ht {
        deny all;
    }
}
